> Importing libraries 

In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


> Getting the dataset


In [23]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [24]:
print(dataset,"\n\n", x,"\n\n", y)



   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes 

 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]] 

 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


>Handling Missing data

In [26]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'median')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [27]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 38.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

> Encoding categorical variable (Independant variable)


In [28]:
from sklearn.compose import ColumnTransformer 
from sklearn.preprocessing import OneHotEncoder 
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))


In [29]:
np.set_printoptions(suppress=True)
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


>Encoding dependant variable

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state = 1)

In [32]:
print(x_train,"\n\n",x_test,"\n\n",y_train,"\n\n",y_test,"\n\n")

[[0.0 0.0 1.0 38.0 52000.0]
 [0.0 1.0 0.0 40.0 61000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]] 

 [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]] 

 [0 1 0 0 1 1 0 1] 

 [0 1] 




>Feature Scaling

In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[: , 3:] = sc.fit_transform(x_train[: , 3:])
x_test[: , 3:] = sc.transform(x_test[: , 3:])



In [34]:
x_train

array([[0.0, 0.0, 1.0, -0.28942984211696865, -1.0430254692900243],
       [0.0, 1.0, 0.0, 0.0, -0.2767210428728636],
       [1.0, 0.0, 0.0, 0.5788596842339373, 0.659873256081444],
       [0.0, 0.0, 1.0, -0.28942984211696865, -0.2767210428728636],
       [0.0, 0.0, 1.0, -1.8812939737602963, -1.383605214364318],
       [1.0, 0.0, 0.0, 1.1577193684678746, 1.2558878099614579],
       [0.0, 1.0, 0.0, 1.4471492105848434, 1.5964675550357514],
       [1.0, 0.0, 0.0, -0.7235746052924217, -0.5321558516785838]],
      dtype=object)

In [35]:
x_test

array([[0.0, 1.0, 0.0, -1.4471492105848434, -0.8727355967528775],
       [1.0, 0.0, 0.0, -0.434144763175453, 0.2341485747385769]],
      dtype=object)

In [1]:
dog = "fish"
dog.replace("i", "o")

'fosh'

In [2]:
def pig(dog, fox):
    return fox + dog
pig("fish", "lion")

'lionfish'

In [3]:
def fox(egg):
    egg = egg + 1
    return egg
egg = 3
fox(egg)

4

In [5]:
def add(a,b):
    return a+b
add(1,2)

3

In [9]:
def swap(word):
    return word[-1]+word[1:-1]+word[0]
swap("labyrinthe")

'eabyrinthl'

In [16]:
def cloak(a):
    if a>12:
        return a-12
    if a==12:
        return 0
    else:
        return a
cloak(12)

0

In [21]:
#Remove equal ends
def equal_ends(a):
    if a[0] == a[-1]:
        return a[1:-1]
    else:
        return a
equal_ends("alohs")
    

'alohs'

In [39]:
def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n-1)
    
factorial(5)
        


120

In [41]:
def fib(n):
    if n<=1:
        return n
    else:
        return(fib(n-1)+fib(n-2))
fib(6
   )
    
    

5